beta0.0.1/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :admins
  resources :users
  
  resources :personalities
  resources :winds
  resources :types
  resources :strongholds
  resources :senseis
  resources :rings
  resources :regions
  resources :monk_shugenja_attachments
  resources :holdings
  resources :followers
  resources :events
  resources :attachments
  resources :acts
  resources :regions
  resources :welcome, as: 'home'
  resources :wishes

  get '/home' => 'home/#index'
  get '/awesome' => 'welcome#awesome_sauce'
  
  get 'admin_user'	=> 'admin/dashboard#index'

  get 'welcome/index'
  root 'welcome#index'

end

beta0.0.1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tables = ["Actions", "Attachments", "Events", "Followers", "Holdings", "Monk-Shugen Attachments", "Personalities", "Regions", "Rings", "Senseis", "Strongholds", "Types", "Winds"]
  end
end

beta0.0.1/app/views/welcome/awesome_sauce.html.erb
<% provide(:title, "Awesome Sauce") %>
<% provide(:jumbotron, '
    <p>Team Ginger: Awesome Sauce</p>    
'.html_safe)%>

beta0.0.1/app/views/welcome/index.html.erb
<% provide(:title, "Team Ginger") %>
<% provide(:jumbotron, '
    <p>Legend of the Five Rings Database</p>
    <a class="btn btn-primary btn-lg" href="awesome" role="button">Learn more &raquo;</a>
'.html_safe)%>
<% provide(:panel_title, "Card Attributes")%>
<div class="container-fluid">

	<table class="table">
		
			<tr>
				<td> Actions </td>
				<td><%= link_to 'View all Actions', acts_path %></td>
			</tr>
			<tr>
 				<td> Attachments </td>
				<td><%= link_to 'View all Attachments', attachments_path %></td>
			</tr>
			<tr>
				<td> Events </td>
				<td><%= link_to 'View all Events', events_path %></td>
			</tr>
			<tr>
				<td> Followers </td>
				<td><%= link_to 'View all Followers', followers_path %></td>
			</tr>
			<tr>
				<td> Holdings </td>
				<td><%= link_to 'View all Holdings', holdings_path %></td>
			</tr>
			<tr>
				<td> Monk-Shugenja Attachments </td>
				<td><%= link_to 'View all Monk-Shugenja Attachments', monk_shugenja_attachments_path %></td>
			</tr>
			<tr>
				<td> Personalities </td>
				<td><%= link_to 'View all Personalities', personalities_path %></td>
			</tr>
			<tr>
				<td> Regions </td>
				<td><%= link_to 'View all Regions', regions_path %></td>
			</tr>
			<tr>
				<td> Rings </td>
				<td><%= link_to 'View all Rings', rings_path %></td>
			</tr>
			<tr>
				<td> Senseis </td>
				<td><%= link_to 'View all Senseis', senseis_path %></td>
			</tr>
			<tr>
				<td> Strongholds </td>
				<td><%= link_to 'View all Strongholds', strongholds_path %></td>
			</tr>
			<tr>
				<td> Types </td>
				<td><%= link_to 'View all Types', types_path %></td>
			</tr>
			<tr>
				<td> Winds </td>
				<td><%= link_to 'View all Winds', winds_path %></td>
			</tr>
	</table>
</div>