jony/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'welcome/index'

  resources :personalities
  resources :winds
  resources :users
  resources :types
  resources :strongholds
  resources :senseis
  resources :rings
  resources :regions
  resources :personalities
  resources :monk_shugenja_attachments
  resources :holdings
  resources :followers
  resources :events
  resources :attachments
  resources :acts
  resources :actions
  resources :regions
  resources :attachments
  resources :actions
  resources :users
  resources :admin

  root 'welcome#index'

end

jony/app/models/action.rb
class Action < ActiveRecord::Base
end

jony/app/models/admin.rb
class Admin < ActiveRecord::Base
end

jony/app/models/attachment.rb
class Attachment < ActiveRecord::Base
end

jony/app/models/event.rb
class Event < ActiveRecord::Base
end

jony/app/models/follower.rb
class Follower < ActiveRecord::Base
end

jony/app/models/holding.rb
class Holding < ActiveRecord::Base
end

jony/app/models/personality.rb
class Personality < ActiveRecord::Base
end

jony/app/models/region.rb
class Region < ActiveRecord::Base
end

jony/app/models/ring.rb
class Ring < ActiveRecord::Base
end

jony/app/models/sensei.rb
class Sensei < ActiveRecord::Base
end

jony/app/models/stronghold.rb
class Stronghold < ActiveRecord::Base
end

jony/app/models/type.rb
class Type < ActiveRecord::Base
end

jony/app/models/user.rb
class User < ActiveRecord::Base
end

jony/app/models/wind.rb
class Wind < ActiveRecord::Base
end

jony/app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :set_follower, only: [:show, :edit, :update, :destroy]

  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
  end

  # GET /followers/new
  def new
    @follower = Follower.new
  end

  # GET /followers/1/edit
  def edit
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(follower_params)

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render :show, status: :created, location: @follower }
      else
        format.html { render :new }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followers/1
  # PATCH/PUT /followers/1.json
  def update
    respond_to do |format|
      if @follower.update(follower_params)
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { render :show, status: :ok, location: @follower }
      else
        format.html { render :edit }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower.destroy
    respond_to do |format|
      format.html { redirect_to followers_url, notice: 'Follower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follower
      @follower = Follower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follower_params
      params.require(:follower).permit(:typeID, :strength, :chi, :personalHonor, :goldCost, :honorRequirement, :keywords, :description, :focus)
    end
end

jony/app/helpers/acts_helper.rb
module ActsHelper
end

jony/app/helpers/admin_helper.rb
module AdminHelper
end

jony/app/helpers/events_helper.rb
module EventsHelper
end

jony/app/helpers/followers_helper.rb
module FollowersHelper
end

jony/app/helpers/rings_helper.rb
module RingsHelper
end

jony/app/helpers/types_helper.rb
module TypesHelper
end

jony/app/helpers/users_helper.rb
module UsersHelper
end

jony/app/helpers/winds_helper.rb
module WindsHelper
end

jony/app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :typeID %><br>
    <%= f.number_field :typeID %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.number_field :strength %>
  </div>
  <div class="field">
    <%= f.label :chi %><br>
    <%= f.number_field :chi %>
  </div>
  <div class="field">
    <%= f.label :personalHonor %><br>
    <%= f.number_field :personalHonor %>
  </div>
  <div class="field">
    <%= f.label :goldCost %><br>
    <%= f.number_field :goldCost %>
  </div>
  <div class="field">
    <%= f.label :honorRequirement %><br>
    <%= f.number_field :honorRequirement %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :focus %><br>
    <%= f.number_field :focus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jony/app/views/followers/edit.html.erb
<h1>Editing Follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

jony/app/views/followers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Followers</h1>

<table>
  <thead>
    <tr>
      <th>Typeid</th>
      <th>Strength</th>
      <th>Chi</th>
      <th>Personalhonor</th>
      <th>Goldcost</th>
      <th>Honorrequirement</th>
      <th>Keywords</th>
      <th>Description</th>
      <th>Focus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= follower.typeID %></td>
        <td><%= follower.strength %></td>
        <td><%= follower.chi %></td>
        <td><%= follower.personalHonor %></td>
        <td><%= follower.goldCost %></td>
        <td><%= follower.honorRequirement %></td>
        <td><%= follower.keywords %></td>
        <td><%= follower.description %></td>
        <td><%= follower.focus %></td>
        <td><%= link_to 'Show', follower %></td>
        <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
        <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follower', new_follower_path %>

jony/app/views/followers/new.html.erb
<h1>New Follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

jony/app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typeid:</strong>
  <%= @follower.typeID %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @follower.strength %>
</p>

<p>
  <strong>Chi:</strong>
  <%= @follower.chi %>
</p>

<p>
  <strong>Personalhonor:</strong>
  <%= @follower.personalHonor %>
</p>

<p>
  <strong>Goldcost:</strong>
  <%= @follower.goldCost %>
</p>

<p>
  <strong>Honorrequirement:</strong>
  <%= @follower.honorRequirement %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @follower.keywords %>
</p>

<p>
  <strong>Description:</strong>
  <%= @follower.description %>
</p>

<p>
  <strong>Focus:</strong>
  <%= @follower.focus %>
</p>

<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>