jony/config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'welcome/index'

  resources :personalities
  resources :winds
  resources :users
  resources :types
  resources :strongholds
  resources :senseis
  resources :rings
  resources :regions
  resources :personalities
  resources :monk_shugenja_attachments
  resources :holdings
  resources :followers
  resources :events
  resources :attachments
  resources :acts
  resources :actions
  resources :regions
  resources :attachments
  resources :actions
  resources :users
  resources :admin

  root 'welcome#index'

end

jony/app/models/action.rb
class Action < ActiveRecord::Base
end

jony/app/models/admin.rb
class Admin < ActiveRecord::Base
end

jony/app/models/attachment.rb
class Attachment < ActiveRecord::Base
end

jony/app/models/event.rb
class Event < ActiveRecord::Base
end

jony/app/models/follower.rb
class Follower < ActiveRecord::Base
end

jony/app/models/holding.rb
class Holding < ActiveRecord::Base
end

jony/app/models/personality.rb
class Personality < ActiveRecord::Base
end

jony/app/models/region.rb
class Region < ActiveRecord::Base
end

jony/app/models/ring.rb
class Ring < ActiveRecord::Base
end

jony/app/models/sensei.rb
class Sensei < ActiveRecord::Base
end

jony/app/models/stronghold.rb
class Stronghold < ActiveRecord::Base
end

jony/app/models/type.rb
class Type < ActiveRecord::Base
end

jony/app/models/user.rb
class User < ActiveRecord::Base
end

jony/app/models/wind.rb
class Wind < ActiveRecord::Base
end

jony/app/controllers/senseis_controller.rb
class SenseisController < ApplicationController
  before_action :set_sensei, only: [:show, :edit, :update, :destroy]

  # GET /senseis
  # GET /senseis.json
  def index
    @senseis = Sensei.all
  end

  # GET /senseis/1
  # GET /senseis/1.json
  def show
  end

  # GET /senseis/new
  def new
    @sensei = Sensei.new
  end

  # GET /senseis/1/edit
  def edit
  end

  # POST /senseis
  # POST /senseis.json
  def create
    @sensei = Sensei.new(sensei_params)

    respond_to do |format|
      if @sensei.save
        format.html { redirect_to @sensei, notice: 'Sensei was successfully created.' }
        format.json { render :show, status: :created, location: @sensei }
      else
        format.html { render :new }
        format.json { render json: @sensei.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senseis/1
  # PATCH/PUT /senseis/1.json
  def update
    respond_to do |format|
      if @sensei.update(sensei_params)
        format.html { redirect_to @sensei, notice: 'Sensei was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensei }
      else
        format.html { render :edit }
        format.json { render json: @sensei.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senseis/1
  # DELETE /senseis/1.json
  def destroy
    @sensei.destroy
    respond_to do |format|
      format.html { redirect_to senseis_url, notice: 'Sensei was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensei
      @sensei = Sensei.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensei_params
      params.require(:sensei).permit(:typeID, :provinceStrength, :goldProduction, :familyHonor, :keywords, :description)
    end
end

jony/app/helpers/acts_helper.rb
module ActsHelper
end

jony/app/helpers/admin_helper.rb
module AdminHelper
end

jony/app/helpers/events_helper.rb
module EventsHelper
end

jony/app/helpers/rings_helper.rb
module RingsHelper
end

jony/app/helpers/senseis_helper.rb
module SenseisHelper
end

jony/app/helpers/types_helper.rb
module TypesHelper
end

jony/app/helpers/users_helper.rb
module UsersHelper
end

jony/app/helpers/winds_helper.rb
module WindsHelper
end

jony/app/views/senseis/_form.html.erb
<%= form_for(@sensei) do |f| %>
  <% if @sensei.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensei.errors.count, "error") %> prohibited this sensei from being saved:</h2>

      <ul>
      <% @sensei.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :typeID %><br>
    <%= f.number_field :typeID %>
  </div>
  <div class="field">
    <%= f.label :provinceStrength %><br>
    <%= f.number_field :provinceStrength %>
  </div>
  <div class="field">
    <%= f.label :goldProduction %><br>
    <%= f.number_field :goldProduction %>
  </div>
  <div class="field">
    <%= f.label :familyHonor %><br>
    <%= f.number_field :familyHonor %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jony/app/views/senseis/edit.html.erb
<h1>Editing Sensei</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensei %> |
<%= link_to 'Back', senseis_path %>

jony/app/views/senseis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Senseis</h1>

<table>
  <thead>
    <tr>
      <th>Typeid</th>
      <th>Provincestrength</th>
      <th>Goldproduction</th>
      <th>Familyhonor</th>
      <th>Keywords</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @senseis.each do |sensei| %>
      <tr>
        <td><%= sensei.typeID %></td>
        <td><%= sensei.provinceStrength %></td>
        <td><%= sensei.goldProduction %></td>
        <td><%= sensei.familyHonor %></td>
        <td><%= sensei.keywords %></td>
        <td><%= sensei.description %></td>
        <td><%= link_to 'Show', sensei %></td>
        <td><%= link_to 'Edit', edit_sensei_path(sensei) %></td>
        <td><%= link_to 'Destroy', sensei, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensei', new_sensei_path %>

jony/app/views/senseis/new.html.erb
<h1>New Sensei</h1>

<%= render 'form' %>

<%= link_to 'Back', senseis_path %>

jony/app/views/senseis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typeid:</strong>
  <%= @sensei.typeID %>
</p>

<p>
  <strong>Provincestrength:</strong>
  <%= @sensei.provinceStrength %>
</p>

<p>
  <strong>Goldproduction:</strong>
  <%= @sensei.goldProduction %>
</p>

<p>
  <strong>Familyhonor:</strong>
  <%= @sensei.familyHonor %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @sensei.keywords %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sensei.description %>
</p>

<%= link_to 'Edit', edit_sensei_path(@sensei) %> |
<%= link_to 'Back', senseis_path %>